# CodeRabbit Configuration for Krodit Project
# This file configures how CodeRabbit reviews your code

# Language settings
language:
  - typescript
  - javascript
  - tsx
  - jsx

# Review settings
review:
  # Review depth: quick, balanced, or comprehensive
  review_depth: "balanced"
  
  # Automatically review PRs
  auto_review: true
  
  # Review types to enable
  review_types:
    - code_quality
    - security
    - performance
    - best_practices
    - documentation
    - testing

# Paths to include/exclude
paths:
  # Include these paths
  include:
    - "src/**/*"
    - "*.ts"
    - "*.tsx"
    - "*.js"
    - "*.jsx"
  
  # Exclude these paths from review
  exclude:
    - "node_modules/**"
    - ".next/**"
    - "out/**"
    - "build/**"
    - "*.config.js"
    - "*.config.ts"
    - "drizzle/**"
    - ".git/**"

# Code quality rules
code_quality:
  # Check for code smells
  check_code_smells: true
  
  # Check for potential bugs
  check_bugs: true
  
  # Check for security issues
  check_security: true
  
  # Suggest improvements
  suggest_improvements: true

# Documentation
documentation:
  # Check for missing JSDoc comments
  require_jsdoc: false
  
  # Check for README updates
  check_readme: true

# Testing
testing:
  # Check for test coverage
  check_coverage: false
  
  # Suggest test cases
  suggest_tests: true

# Performance
performance:
  # Check for performance issues
  check_performance: true
  
  # Check for memory leaks
  check_memory_leaks: true

# Security
security:
  # Check for security vulnerabilities
  check_vulnerabilities: true
  
  # Check for sensitive data exposure
  check_secrets: true

# Custom instructions for your project
custom_instructions: |
  This is a Next.js 16 project using:
  - TypeScript
  - React 19
  - tRPC for API
  - Drizzle ORM
  - Tailwind CSS
  - Radix UI components
  
  Please focus on:
  - React best practices
  - TypeScript type safety
  - Next.js App Router patterns
  - Component reusability
  - Code organization and maintainability
  - Accessibility (a11y)
  
  The project follows a modular structure with:
  - Modules in src/modules/
  - Shared components in src/components/
  - Server procedures in src/modules/*/server/
  - UI components in src/modules/*/ui/

# PR review settings
pr_review:
  # Review title and description
  review_title: true
  review_description: true
  
  # Review commit messages
  review_commits: true
  
  # Suggest PR improvements
  suggest_improvements: true

# Chat settings (if using CodeRabbit chat)
chat:
  # Enable chat in PRs
  enabled: true
  
  # Auto-respond to questions
  auto_respond: false

